name: SpotifyCatalogAPI tests

permissions:
  contents: read
  actions: read
  checks: write

on:
  pull_request:
    branches:
      - main

jobs:
  Test:
    name: Execute Unittests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run Tests
        run: |
          mvn test -q -Dtest=CatalogUtilsTest,SpotifyUtilsTest

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Maven Surefire Tests
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit         # Correct value for Maven Surefire
          list-suites: all
          list-tests: all
          max-annotations: 10
          fail-on-error: true
          fail-on-empty: true
          only-summary: false
          path-replace-backslashes: false

    TriggerDeployment:
      runs-on: ubuntu-latest
      needs: Build
      env:
        SPOTIFY_TESTING_REPO_NAME: moslem-asaad/SpotifyTesting
        UI_TESTING_WORKFLOW_ID: ui-testing.yaml
      steps:
        - name: Trigger the Selenium testing workflow
          run: |
            curl -X POST \
             -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             -d "{\"ref\": \"main\", \"inputs\": {\"browser\": \"chrome\"}}" \
             https://api.github.com/repos/$SPOTIFY_TESTING_REPO_NAME/actions/workflows/$UI_TESTING_WORKFLOW_ID/dispatches
