name: SpotifyCatalogAPI tests

permissions:
  contents: read
  actions: read
  checks: write

on:
  pull_request:
    branches:
      - main

jobs:
  Test:
    name: Execute Unittests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run Tests
        run: |
          mvn test -q

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: 'target/surefire-reports/TEST-*.xml'    # Path to test results
          reporter: jest-junit        # Format of test results