name: SpotifyCatalogAPI tests

permissions:
  contents: read
  actions: read
  checks: write

on:
  pull_request:
    branches:
      - main

jobs:
  Test:
    name: Execute Unittests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run Tests
        run: |
          mvn test -q -Dtest=CatalogUtilsTest,SpotifyUtilsTest

      - name: Check Styles
        run: |
          mvn checkstyle:check -Dcheckstyle.violationSeverity=warning

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Maven Surefire Tests
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit         # Correct value for Maven Surefire
          list-suites: all
          list-tests: all
          max-annotations: 10
          fail-on-error: true
          fail-on-empty: true
          only-summary: false
          path-replace-backslashes: false

  Test Style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Check Styles
        run: |
          mvn checkstyle:check -Dcheckstyle.violationSeverity=warning

    



