name: SpotifyCatalogAPI tests with spotify testing

on:
  pull_request:
    branches:
      - main

jobs:

  TriggerDeployment:
    runs-on: ubuntu-latest
    needs: Build
    env:
      SPOTIFY_TESTING_REPO_NAME: moslem-asaad/SpotifyTesting
      UI_TESTING_WORKFLOW_ID: ui-testing.yaml
    steps:
      - name: Trigger the Selenium testing workflow
        run: |
          curl -X POST \
           -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
           -H "Accept: application/vnd.github.v3+json" \
           -d "{\"ref\": \"main\", \"inputs\": {\"browser\": \"chrome\"}}" \
           https://api.github.com/repos/$SPOTIFY_TESTING_REPO_NAME/actions/workflows/$UI_TESTING_WORKFLOW_ID/dispatches